### ISSUE TITLE
change event is emitted with just one boolean argument, while docs say there should be two

### ISSUE THREAD

**Issue by WDeenik** [LinusBorg/portal-vue#254]
The [docs](https://portal-vue.linusb.org/api/portal-target.html#events-api) say a `change` event handler should receive two Boolean arguments, `newContent` and `oldContent`. 

However, it only [emits](https://github.com/LinusBorg/portal-vue/blob/80b0a32be441ff978a6b85388d41ae0b2a62f488/src/components/portal-target.tsx#L33) one argument, so either the documentation or the implementation is wrong.

**Comment by LinusBorg** [comment]
Thanks fpr bringing this to my attention!

Weird, though - Thought I fixed that ages ago...

**Comment by WDeenik** [comment]
Glad I could help!

Makes sense, we can do exactly the same with just the one argument, just expected I could use `oldContent` as well in my handler.

**Comment by LinusBorg** [comment]
In the warning box after the code example it already meantions the correct, new implementation ^^

I just seem to have forgot to fixe the text before the example and the example itself or something.

**Comment by WDeenik** [comment]
Ah, I read the warning box in the same way. Partly because of the text above, partly because it is still not that clear about the number of arguments you get:

> The event now is simple Boolean value**s**, indicating wether the target **is/was** empty or not.
